### ISSUE TITLE
Out-Word throws an error with Office 2013 and PowerShell v2

### ISSUE THREAD

**Issue by samratashok** [samratashok/nishang#22]
A user Greg reported this on twitter
https://twitter.com/gregkcarson/status/623916646172786688

Greg is trying this on PowerShell v3. Information awaited.

**Comment by gregkcarson** [comment]
Failed again after upgrading to PowerShell v3.

Running Windows 7 Professional SP 1 64bit.
Office 2013
Tried PowerShell v2 and v3
Tried running CMD prompt as admin and non-admin.

From the nishang-master\client directory I executed:
1.  . .\Out-Word.ps1
-followed by
2. Out-Word -Payload "powershell.exe -ExecutionPolicy Bypass -noprofile -noexit -c Get-Process"

**Comment by samratashok** [comment]
Let me try to reproduce it.

**Comment by gregkcarson** [comment]
After the error it says the file is saved but the prompt hangs and no file appears.
![testing](https://cloud.githubusercontent.com/assets/11640674/8833970/849dce78-3066-11e5-971d-25ab28e63eca.PNG)

**Comment by samratashok** [comment]
Unable to reproduce. Tried on a Windows 7 with PowerShell v2 and Office 2013. Try running the script from a PowerShell prompt. I think the problem is the way you are using the script.

**Comment by gregkcarson** [comment]
My method:
- Download ZIP from github page
- Place in C:\Users\gcarson directory
- Extract contents
- Open a command prompt as administrator
- type PS to load powershell
- CD to nishang-master\client\ directory
Copy paste in:
1. . .\Out-Word.ps1
-followed by
2. Out-Word -Payload "powershell.exe -ExecutionPolicy Bypass -noprofile -noexit -c Get-Process"

**Comment by samratashok** [comment]
You don't seem to be doing anything wrong but I am still unable to reproduce. Try:

1. Running from normal (non-administrative) PowerShell prompt.
2. What is the output of this on your test machine?:  (New-Object -ComObject Word.Application).Version
Since you are running Office 2013, you should see 15.0 as output. 
3. Please share the output of $PSVersionTable in PowerShell. I just want to make sure if there is dependency on .Net version which I am unaware of.

**Comment by gregkcarson** [comment]
Output for Question 2: 15.0
Output for Question 3:
PS Version 3.0
WSManStackVersion 3.0
SerializationVersion 1.1.0.1
CLRVersion 4.0.30319.18444
BuildVersion 6.2.9200.16398
PSRemotingProtocolVersion 2.2

**Comment by samratashok** [comment]
$Word = New-Object -ComObject Word.Application
$Word.DisplayAlerts = "wdAlertsNone"

Do you receive an error? 

Try 

$Word.DisplayAlerts = $False

**Comment by gregkcarson** [comment]
I will try this on Monday and let you know - was out of office today.

I'm going to try installing everything on a different machine over the weekend and see if I can get better results. Will let you know.

**Comment by gregkcarson** [comment]
Here's the result : 
![results](https://cloud.githubusercontent.com/assets/11640674/8938345/f2695f20-3512-11e5-8e12-477bc7af46a3.PNG)

**Comment by gregkcarson** [comment]
Also can you let me know what virtualization software you are using? If you are just using trial windows 7 image and trial office in virtualbox and it works without issue then perhaps I will do the same and copy the file back to my system.

**Comment by samratashok** [comment]
I am using VMware. Tried the code on home and enterprise editions of Windows 7m it works fine for me. Try replacing this code in the script:
    if (($WordVersion -eq "12.0") -or  ($WordVersion -eq "11.0"))
    {
        $Word.DisplayAlerts = $False
    }
    else
    {
        $Word.DisplayAlerts = "wdAlertsNone"
    } 


with this code

$Word.DisplayAlerts = $False

Though above may not be the right way but see if it works.

**Comment by samratashok** [comment]
Did you get a chance to test the above code?

**Comment by gregkcarson** [comment]
Not yet - just finishing up a couple projects and packing for Black Hat. Should be able to test it when I get back from DEFCON on the 10th :)

**Comment by samratashok** [comment]
Find me there and get your issue resolved :)

**Comment by samratashok** [comment]
Could you please update me on this?

**Comment by gregkcarson** [comment]
I replaced those lines as you mentioned previously and ran the command. The command finished without error but it did not produce a "saved to file C:\path\path\etc" message. I checked in the install directory and I do not see any file created anywhere.

**Comment by samratashok** [comment]
Still unable to reproduce the bug :(

**Comment by samratashok** [comment]
Closing due to inability to reproduce.
