### ISSUE TITLE
MS16-065- TLS/SSL Protocol update

### ISSUE THREAD

**Issue by Cyb3rWard0g** [samratashok/nishang#39]
This update affects the way how the encryption component of .NET sends and receives encrypted packets. It splits the first record after the handshake (1byte + remaining bytes). I was modifying my own scripts and was testing your Invoke-PoshRatHTTPs with them. I couldnt figure out why I was getting the packets split. I just had to change the protocol to TLS12 from TLS on your script and my own client.

More specific:
$SslStream.AuthenticateAsServer($SSLcertfake, $false, [System.Security.Authentication.SslProtocols]::Tls12, $false)

I figured I let you know so that the script is up to date, and help others with the same issue.

P.S. Amazing job and thank  you for sharing your knowledge ! :+1: 

Reference:
https://support.microsoft.com/en-us/kb/3155464

**Comment by samratashok** [comment]
Great! Thanks a ton! I will update the script.

**Comment by cloudwafs** [comment]
Great!
