### ISSUE TITLE
No output produced

### ISSUE THREAD

**Issue by Indeserpen** [samratashok/nishang#48]
Hello!

Im running into issues with outout ExetoText, maybe me i am doing something incorrectly!
PS C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility> .\ExetoText.ps1 C:\Users\Admin\Documents\WindowsP
owerShell\Modules\nishang\Utility\crss.exe C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility\crss.txt
PS C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility>

And there is no output!

**Comment by samratashok** [comment]
You need to load the script using dot sourcing. 

PS C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility>.  .\ExetoText.ps1
PS C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility> ExetoText C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility\crss.exe C:\Users\Admin\Documents\WindowsPowerShell\Modules\nishang\Utility\crss.txt

**Comment by samratashok** [comment]
Closing. No response received.

**Comment by Indeserpen** [comment]
yes thanks all good now!!
