### ISSUE TITLE
Out-word.ps1 error

### ISSUE THREAD

**Issue by srihari-humbarwadi** [samratashok/nishang#49]
PS C:\Users\eMO\desktop> . ./Out-word.ps1
PS C:\Users\eMO\desktop> Out-Word -Payload "powershell.exe -ExecutionPolicy Bypass -noprofile -noexit -c Get-Process" -RemainSafe
You cannot call a method on a null-valued expression.
At C:\Users\eMO\desktop\Out-Word.ps1:357 char:9
+         $DocModule = $Doc.VBProject.VBComponents.Item(1)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\eMO\desktop\Out-Word.ps1:358 char:9
+         $DocModule.CodeModule.AddFromString($code_one)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Saved to file C:\Users\eMO\desktop\Salary_Details.doc
0
PS C:\Users\eMO\desktop>

**Comment by srihari-humbarwadi** [comment]
![error](https://cloud.githubusercontent.com/assets/24864163/21640467/b1429638-d29b-11e6-9031-15e67ef1853f.png)

**Comment by samratashok** [comment]
Do you have MS Word installed on the machine where you are running the Out-Word script?

**Comment by srihari-humbarwadi** [comment]
Yes I have office 13

**Comment by samratashok** [comment]
Does Out-Excel throws a similar error?

**Comment by srihari-humbarwadi** [comment]
Reinstalling MS office solved the part. but when i open the word file nothing happens.
so i tried putting single quote  then this happened 
PS C:\Users\eMO\desktop> out-word -Payload " powershell.exe -noexit -c Invoke-Expression $(New-Object IO.StreamReader ($
(New-Object IO.Compression.DeflateStream ($(New-Object IO.MemoryStream (,$([Convert]::FromBase64String(''c08t0Q0oyk9OLS7
m5QIA'')))), [IO.Compression.CompressionMode]::Decompress)), [Text.Encoding]::ASCII)).ReadToEnd();"
At line:1 char:201
+ ... Base64String(''c08t0Q0oyk9OLS7m5QIA'')))), [IO.Compression.CompressionMode]::Dec ...
+                    ~
Missing ')' in method call.
At line:1 char:201
+ ... Base64String(''c08t0Q0oyk9OLS7m5QIA'')))), [IO.Compression.CompressionMode]::Dec ...
+                    ~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'c08t0Q0oyk9OLS7m5QIA''' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

**Comment by srihari-humbarwadi** [comment]
At line:1 char:201
+ ... Base64String(''c08t0Q0oyk9OLS7m5QIA'')))), [IO.Compression.CompressionMode]::Dec ...
+                    ~
Missing ')' in method call.
At line:1 char:201
+ ... Base64String(''c08t0Q0oyk9OLS7m5QIA'')))), [IO.Compression.CompressionMode]::Dec ...
+                    ~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'c08t0Q0oyk9OLS7m5QIA''' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

**Comment by srihari-humbarwadi** [comment]
Reinstalling MS office solved the part. but when i open the word file nothing happens.
so i tried putting single quote then this happened


PS C:\Users\eMO\desktop> out-word -Payload " powershell.exe -noexit -c Invoke-Expression $(New-object IO.StreamReader ($(New-Object IO.Compression.DeflateStream ($(New-Object IO.MemoryStream (,$([Convert]::FromBase64String(''c08t0Q0oyk9OLS7m5QIA'')))), [IO.Compression.CompressionMode]::Decompress)), [Text.Encoding]::ASCII)).ReadToEnd();"



error in the pic

**Comment by srihari-humbarwadi** [comment]
![error](https://cloud.githubusercontent.com/assets/24864163/21684911/8af88416-d385-11e6-92a5-b2b4c8488ab2.png)

**Comment by srihari-humbarwadi** [comment]
Microsoft Word 2010
This document was edited in a different version of Microsoft Word.
To load the document, please Enable Content


 this is what i get when i dont include single quotes

**Comment by samratashok** [comment]
That is a trick to entice a user to enable Macros. The payload gets executed. Have a look at running processes you will see an additional powershell.exe process.

**Comment by srihari-humbarwadi** [comment]
my script which is 400 lines, when i try to encode it with invoke-encode it give me the same result for for 
-outcommand and -postscriptcommand

. ./invoke-encoded.ps1
invoke-encode -DataToEncode main.ps1 -Outcommand

when i run this i get Output as PostScriptCommand
PS : Generated PostScriptCommand is valid.  but i am not able to get the right form of output

Interesting thing is, small scripts work fine

**Comment by srihari-humbarwadi** [comment]
![error](https://cloud.githubusercontent.com/assets/24864163/21744695/e50895ce-d540-11e6-89af-f7f319d8cc67.png)
