### ISSUE TITLE
PROBLEM with PowerShell! (Invoke-PowerShellTcpOneLine.ps1)

### ISSUE THREAD

**Issue by DiegoSepu95** [samratashok/nishang#53]
![screen shot 2017-04-11 at 1 53 36 pm](https://cloud.githubusercontent.com/assets/23207649/24925605/621a6224-1ebe-11e7-968c-0ddd48763b07.png)
I get this error when trying to run this, any suggestions? Im using it on VMWare Win10 (virtual machine). It actually downloads the .ps1 but it fails to run it.

**Comment by samratashok** [comment]
Hi, 

Never seen this before. Can't reproduce as well :/
