### ISSUE TITLE
Shells/Invoke-PowershellTCPOneLine: A positional parameter cannot be found that accepts argument 'System.Net.Sockets.NetworkStream'.

### ISSUE THREAD

**Issue by kileraptor1** [samratashok/nishang#55]
![screenshot_327](https://cloud.githubusercontent.com/assets/20141618/26426131/978b6cec-40d7-11e7-8275-5caea3d15892.png)

**Comment by samratashok** [comment]
Don't know if its a question or a you are trying to raise an issue/bug but the code works fine for me. You need not use Invoke-Expression here as you are already running the code in a PowerShell console.
