### ISSUE TITLE
Import-Module

### ISSUE THREAD

**Issue by Ub3rKristy** [samratashok/nishang#56]
Hello, community! 

PS write this error:

`Import-Module : File C:\nishang\nishang.psm1 cannot be loaded because the execution of scripts is disabled on this system.`

What will I do?

P.S. I use win7x64

**Comment by samratashok** [comment]
You can use "powershell -ep bypass" to set execution policy to bypass for the new PowerShell process.

**Comment by Ub3rKristy** [comment]
@samratashok thank you!
