### ISSUE TITLE
Why when trying Out-CHM,it will exe twice every operation? 

### ISSUE THREAD

**Issue by ilovejiang** [samratashok/nishang#60]
God I need help!
when trying the Out-CHM cilent ,  open the chm file generated , it will push the calc.exe(which i use to be the backdoor.exe) twice?

**Comment by samratashok** [comment]
Need more details. What do you mean by push? Does it execute the payload twice?

P.S. I am no God :)

**Comment by ilovejiang** [comment]
Exactly what you say the payload exe twice
I notice the “x.click()” may be the key but I just don’t know why it leads the payload exed mtwice when I open the chm
Thanks for reply  

发送自 Windows 10 版邮件应用

发件人: samratashok
发送时间: 2017年12月7日 17:28
收件人: samratashok/nishang
抄送: ilovejiang; Author
主题: Re: [samratashok/nishang] Why when trying Out-CHM,it will exe twiceevery operation? (#60)

Need more details. What do you mean by push? Does it execute the payload twice?
P.S. I am no God :)

**Comment by samratashok** [comment]
The payload is executed just once by default. But if yo click on the first and third help topics in the generated CHM, the payload gets executed on each click.

**Comment by ilovejiang** [comment]
i didn't use a payload in your .ps , but i rewrite your ps_code , put the calc.exe linkage into the JS code to replace the "$payload" para.
then , i just double cilck the chm file ,when it opens , calc.exe will pop twice, even if i didn't do anything else.
And i also test the ori file , the cmd.exe will pop twice too.

**Comment by samratashok** [comment]
Don't know why you are facing this. Could you please share the code?

**Comment by ilovejiang** [comment]
Sorry for replying late . 
Should i email the code to you ? May you could give me some help.
Thanks

**Comment by samratashok** [comment]
Please share a gist.

**Comment by ilovejiang** [comment]
Here is the link!
https://gist.github.com/ilovejiang/3ea8d9590f96f7759c0deffb4c85c90b
Thanks

**Comment by samratashok** [comment]
calc pops up just once for me :/

**Comment by ilovejiang** [comment]
（‘’—。—‘’）well,could you please tell me your steps when retrying this? for you open powershell as the start.......

**Comment by samratashok** [comment]
Sure. I simply saved your code and used it. Calc pops just once.
![out-chmtest](https://user-images.githubusercontent.com/1753291/33948159-37fba2fa-e04c-11e7-868e-066e9bcecd13.png)

**Comment by samratashok** [comment]
Any update on this? Else I would like to close the issue.
