### ISSUE TITLE
Apt-get install Forbidden IP Kali Linux

### ISSUE THREAD

**Issue by adamhart** [samratashok/nishang#61]
Hello

While running apt-get update in Kali Linux I am receiving the below error for the package nishang:

Failed to fetch http://archive-9.kali.org/kali kali-rolling/main amd64 nishang all 0.7.6-0kali1_all.deb 403 Forbidden [IP: 167.114.191.148 80]

I have tried other mirrors but they all report the same above Forbidden error.

If this issue needs to be reported to Kali or the apt team please let me know and close this issue.

Thanks.

**Comment by samratashok** [comment]
Yes, I believe it needs to be reported to the Kali team.
