### ISSUE TITLE
Error running Get-LsaSecret

### ISSUE THREAD

**Issue by githubtran** [samratashok/nishang#64]
when running Get-LsaSecret I am getting this error on every secret name:
WARNING: lsaNtsStatusToWinError: 1305
Cannot convert null to type "LSAUtil.LSAUtil+LSA_UNICODE_STRING".
At C:\temp\get-lsasecret.ps1:214 char:101
+         [LSAUtil.LSAUtil+LSA_UNICODE_STRING][System.Runtime.InteropServices.marshal]::PtrToStructure <<<< ($privateData, [System.Type][LSAUtil.LSAUtil+LSA_UNICODE_STRING])
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

**Comment by samratashok** [comment]
Which Windows version? Which PowerShell version?

**Comment by githubtran** [comment]
Windows Server 2008 R2 with Powershell v2.0

**Comment by samratashok** [comment]
Never tested this on Server 2008. From your error it looks like there some type conversion issues. Can't commit that I will do this but please give me some time to test this.

**Comment by githubtran** [comment]
Thank you.  It could be the Powershell version.  Let's me see if I can upgrade to Powershell v4 and test again.

**Comment by githubtran** [comment]
Upgrade to Powershell v4 fixed the error.  Thanks.
