### ISSUE TITLE
[Question] What's the meaning of `nishang`?

### ISSUE THREAD

**Issue by CSharperMantle** [samratashok/nishang#80]
This is a relatively silly question, and I will try not to be like a dick.
I am a Chinese. I came across with `nishang` and liked it very much. My question is that what does the word `nishang` actually mean. In Chinese, there is a word "你上" with exactly the same pronunciation ("Nǐ Shàng" in Pinyin), which means "it's your turn and go ahead". I am wondering if there are any connections between these two words. Thanks very much!

**Comment by samratashok** [comment]
I think someone told me about the Chineese word earlier too :) The word Nishang in Sanskrit language means a quiver (to hold arrows)
